### ISSUE TITLE
Thing we need to decide before we can continue is the following

### ISSUE THREAD

**Issue by Mupen** [Mupen/SchoolManagement-Assignment5#1]
### **Package structure and project structure **
my recommendation is to use this structure.

**_default_** 

> Were we keep main or app.

**_controller_** 

> We could have menuController and ViewController unsure about this one as i have not worked with them as much.

**_data_** 

> Will be were we keep the interaction with the ArrayList. for studentDao and courseDao

**_model_** Model represents an object or JAVA POJO carrying data. It can also have logic to update controller if its data changes.

> Will be were we keep studentModel and courseModel

**_service_** 

> Will be were we keep studentService and courseService and implement interfaces for them

**_utility_** 

> Will be were we keep useful method that would stand out in other locations

**Comment by MariaHofstam** [comment]
Fine by me.
